when:
  - event: push
    branch: master
  - event: cron
    cron: "daily build"

steps:
  - name: Build container
    image: plugins/kaniko
    settings:
      registry: https://registry.fuwafuwatime.moe
      repo: registry.fuwafuwatime.moe/concord/asterisk-use-callmanager
      dockerfile: Containerfile
      build-args:
        - ASTERISK_VERSION=${CI_COMMIT_TAG}
      tags:
        - ${CI_COMMIT_TAG:-${CI_COMMIT_SHA}}
        - latest
      username:
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASS
